### ISSUE TITLE
Initial objectives.

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/CAyZ#6]
Players will need something to do, and initially they (probably?) won't be able to travel far.  Let's mark out some objectives around the campsite for them to complete, and build setpieces around them.  

A small number, enough to fill a single ~2h timeslot.  Probably ~3-4 close-by or 2-3 close-to-distant.

Objectives will be defined by the players' motivations, so #1 is a prerequisite.
Objectives will be positioned near the camp, so #2 is a prerequisite.
Objectives may be guarded or held by factions.  If so, #4 is required for each of those.

**Comment by Bubbus** [comment]
Waiting on closure of #1, once done we can identify one of the objectives mentioned in-wiki to implement in Iteration 1.

This task will probably generate some tasks in the Setpieces project depending on the choice of first implemented objective, and a follow-on task for specific implementation of the objective.

**Comment by dgibso29** [comment]
#1 is closed.

First objectives should be focused on supplies, transport, and arms. 

- 1: They should be okay on food at start because it's the Meat Up, but medical & possibly water will be low. 
- 2: Few or no vehicles at start (at most a couple civie civs with low fuel....? Dunno). They'll need fuel and more/better vics, plus supplies to repair them
- 3: Very few guns and low ammo at start. Will need more + likely want to try to find better kit (light armour, etc)
